### PR TITLE
Add sprintf formatting for column names in coerce_values.

### PR DESCRIPTION
**Pull request by Wilfred**
Fixes https://github.com/logstash-plugins/logstash-output-influxdb/issues/9 .

### CODE REVIEW

**Comment by brupm** [comment]
@Wilfred please add more details and a test case otherwise @jordansissel close it?

**Comment by Wilfred** [comment]
I often find myself writing:

```
input {
    udp {
        port => 25826
        buffer_size => 1452
        codec => collectd { }
    }
}

output {
    if [collectd_type] == "memory" or [collectd_type] == "cpu" or [collectd_type] == "swap" or [collectd_type] == "if_octets" or [collectd_type] == "df_complex" {
        influxdb {
            host => "example.com"
            db => "metrics"
            user => "foo"
            password => "bar"
            series => "%{host}"
            data_points => {"%{collectd_type}.%{type_instance}" => "%{value}"}
            coerce_values => {"%{collectd_type}.%{type_instance}" => "float"}
        }
    }
}
```

Without supporting sprintf_formatting for `coerce_values`, I'm forced to duplicate my `influxdb` section.

Does that seem reasonable? I'm happy to add some tests.

**Comment by brupm** [comment]
Tests would be awesome!

**Comment by suyograo** [comment]
@Wilfred can you rebase, add tests and reopen a new PR?. I am going to close this PR since master has deviated with #29 and #30. Thanks much

**Pull request closed without merging**
