### PR TITLE
Fix issue #22

### PR DESCRIPTION
**Pull request by albanf**
Fix issue #22 and add time precisions supported by InfluxDB 0.9

### CODE REVIEW

**Comment by purbon** [comment]
Thanks a lot for your contribution @albanf, it would be super nice if you can add test for this change. We try to enforce that all PR introduce some kind of testing, so we're able to increase the overall quality. Don't hesitate to ask any question regarding you might have, more than looking forward to help.

/cheers

**Comment by jordansissel** [comment]
I don't know much about influxdb, but the proposed change looks ok - code and idea +1. Haven't tested.

**Comment by purbon** [comment]
@albanf still looking for some test for this change, can you provide them? if not, I can help you somehow, but like @jordansissel I have no knowledge of influxdb, so would require some external help, but certanly can help with rspec knowhow :+1:

**Comment by suyograo** [comment]
Fixed in #30 and #29

**Pull request closed without merging**
